document.writeln("<script type=\'text/javascript\' src=\'/statics/ads/js/jquery.js\'></script>");
document.writeln("<script type=\'text/javascript\' src=\'/statics/ads/js/superslide.2.1.js\'></script>");
document.writeln("<style type=\'text/css\'>		");
document.writeln("*{margin:0;padding:0;list-style:none;}");
document.writeln("body{background:#fff;font:normal 12px/22px 宋体;width:100%;}");
document.writeln("img{border:0;}");
document.writeln("a{text-decoration:none;color:#333;}");
document.writeln("a:hover{color:#1974A1;}");
document.writeln("/* fullSlide */");
document.writeln(".fullSlide{width:100%;position:relative;height:390px;background:#000;}");
document.writeln(".fullSlide .bd{margin:0 auto;position:relative;z-index:0;overflow:hidden;}");
document.writeln(".fullSlide .bd ul{width:100% !important;}");
document.writeln(".fullSlide .bd li{width:100% !important;height:390px;overflow:hidden;text-align:center;}");
document.writeln(".fullSlide .bd li a{display:block;height:390px;}");
document.writeln(".fullSlide .hd{width:100%;position:absolute;z-index:1;bottom:0;left:0;height:30px;line-height:30px;}");
document.writeln(".fullSlide .hd ul{text-align:center;}");
document.writeln(".fullSlide .hd ul li{cursor:pointer;display:inline-block;*display:inline;zoom:1;width:42px;height:11px;margin:1px;overflow:hidden;background:#000;filter:alpha(opacity=50);opacity:0.5;line-height:999px;}");
document.writeln(".fullSlide .hd ul .on{background:#f00;}");
document.writeln(".fullSlide .prev,.fullSlide .next{display:block;position:absolute;z-index:1;top:50%;margin-top:-30px;left:15%;z-index:1;width:40px;height:60px;background:url(/statics/ads/img/slider-arrow.png) -126px -137px #000 no-repeat;cursor:pointer;filter:alpha(opacity=50);opacity:0.5;display:none;}");
document.writeln(".fullSlide .next{left:auto;right:15%;background-position:-6px -137px;}");
document.writeln("</style>");
document.writeln("");
document.writeln("<div class=\'fullSlide\'>");
document.writeln("	<div class=\'bd\'>");
document.writeln("		<ul>");
document.writeln("");
document.writeln("");



document.writeln("			<li _src=\'url(/statics/ads/img/1.jpg)\' style=\'background:#E2025E center 0 no-repeat;\'><a href=\'https://1495d6.com/PageRegister?Agent=lwqcoco\' target=\'_blank\'></a></li>");
document.writeln("			<li _src=\'url(/statics/ads/img/2.jpg)\' style=\'background:#DED5A1 center 0 no-repeat;\'><a href=\'https://1495d6.com/PageRegister?Agent=lwqcoco\' target=\'_blank\'></a></li>");
document.writeln("			<li _src=\'url(/statics/ads/img/3.jpg)\' style=\'background:#B8CED1 center 0 no-repeat;\'><a href=\'https://1495d6.com/PageRegister?Agent=lwqcoco\' target=\'_blank\'></a></li>");
document.writeln("			<li _src=\'url(/statics/ads/img/4.jpg)\' style=\'background:#98918E center 0 no-repeat;\'><a href=\'https://1495d6.com/PageRegister?Agent=lwqcoco\' target=\'_blank\'></a></li>");


document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("		</ul>");
document.writeln("	</div>");
document.writeln("	<div class=\'hd\'><ul></ul></div>");
document.writeln("	<span class=\'prev\'></span>");
document.writeln("	<span class=\'next\'></span>");
document.writeln("</div><!--fullSlide end-->");
document.writeln("  ");
document.writeln("  ");
document.writeln("<script type=\'text/javascript\'>");
document.writeln("$(\'.fullSlide\').hover(function(){");
document.writeln("    $(this).find(\'.prev,.next\').stop(true, true).fadeTo(\'show\', 0.5)");
document.writeln("},");
document.writeln("function(){");
document.writeln("    $(this).find(\'.prev,.next\').fadeOut()");
document.writeln("});");
document.writeln("$(\'.fullSlide\').slide({");
document.writeln("    titCell: \'.hd ul\',");
document.writeln("    mainCell: \'.bd ul\',");
document.writeln("    effect: \'fold\',");
document.writeln("    autoPlay: true,");
document.writeln("    autoPage: true,");
document.writeln("    trigger: \'click\',");
document.writeln("    startFun: function(i) {");
document.writeln("        var curLi = jQuery(\'.fullSlide .bd li\').eq(i);");
document.writeln("        if ( !! curLi.attr(\'_src\')) {");
document.writeln("            curLi.css(\'background-image\', curLi.attr(\'_src\')).removeAttr(\'_src\')");
document.writeln("        }");
document.writeln("    }");
document.writeln("});");
document.writeln("</script>");